spring:
  jpa:
      hibernate:
        ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
#    properties:
#      javax.persistence.query.timeout: 30000
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyze_deals
    username: postgres
    password: postgres
  logging:
    pattern:
      console: "%-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug

  server:
    port: 8585